# Generated by Django 4.2.3 on 2023-08-10 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='path_instructor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.instructor'),
        ),
        migrations.AddField(
            model_name='path',
            name='chef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_paths', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='branche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_the_branche', to='courses.branche'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='branche',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_the_path', to='courses.path'),
        ),
    ]
