# Generated by Django 4.2.3 on 2023-08-21 14:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_branche_id_alter_course_id_alter_path_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path_instructor',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
