# Generated by Django 4.2.3 on 2023-08-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('courses', '0007_course_participation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course_participation',
            unique_together={('course', 'developer')},
        ),
    ]
