# Generated by Django 4.2.3 on 2023-08-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_delete_course_answer'),
        ('courses', '0008_alter_course_participation_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course_Participation',
        ),
    ]
