# Generated by Django 4.2.3 on 2023-08-15 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('challenges', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('title', 'Title'), ('text', 'Text'), ('picture', 'Picture'), ('video', 'Video'), ('file', 'File'), ('question', 'Question')], max_length=10)),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.content')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.content')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.content')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_tasks', to='challenges.challenge')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_tasks', to='courses.course')),
            ],
            options={
                'unique_together': {('number', 'challenge'), ('number', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('solution', models.CharField(max_length=100)),
                ('hint', models.TextField()),
                ('points', models.IntegerField(default=0)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.content')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='photos/')),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.content')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.content')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='tasks.task'),
        ),
    ]
