# Generated by Django 4.2.3 on 2023-08-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('title', 'Title'), ('text', 'Text'), ('picture', 'Picture'), ('video', 'Video'), ('file', 'File'), ('question', 'Question')], max_length=25),
        ),
    ]
