# Generated by Django 4.2.3 on 2023-08-20 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_content_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_file', to='tasks.content'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_picture', to='tasks.content'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_question', to='tasks.content'),
        ),
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_text', to='tasks.content'),
        ),
        migrations.AlterField(
            model_name='title',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_title', to='tasks.content'),
        ),
        migrations.AlterField(
            model_name='video',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_video', to='tasks.content'),
        ),
    ]
