# Generated by Django 4.2.3 on 2023-08-22 11:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_participation'),
        ('tasks', '0004_alter_file_content_alter_picture_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_anwers', to='courses.course_participation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.question')),
            ],
        ),
    ]
