# Generated by Django 4.2.3 on 2023-08-22 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_participation_unique_together'),
        ('tasks', '0005_course_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_answer',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_answers', to='courses.course_participation'),
        ),
    ]
