# Generated by Django 4.2.3 on 2023-08-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_course_answer_participation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course_Answer',
        ),
    ]
