# Generated by Django 4.2.3 on 2023-08-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='photos/courses/')),
                ('max_participants', models.IntegerField()),
                ('challenge_type', models.CharField(choices=[('JOB', 'Job'), ('COMPETITION', 'Competition')], max_length=50)),
            ],
        ),
    ]
