# Generated by Django 4.2.3 on 2023-08-20 19:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_competition_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challenge_type',
            field=models.CharField(blank=True, choices=[('JOB', 'Job'), ('COMPETITION', 'Competition')], max_length=50),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
