# Generated by Django 4.2.3 on 2023-08-22 15:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('courses', '0009_delete_course_participation'),
        ('tasks', '0007_delete_course_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Participation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.developer')),
            ],
            options={
                'unique_together': {('course', 'developer')},
            },
        ),
        migrations.CreateModel(
            name='Course_Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_answers', to='participation.course_participation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.question')),
            ],
        ),
    ]
