# Generated by Django 4.2.3 on 2023-08-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_participation',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
