# Generated by Django 4.2.3 on 2023-08-22 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_content_id_alter_file_id_alter_picture_id_and_more'),
        ('participation', '0002_course_participation_is_finished'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course_answer',
            unique_together={('participation', 'question')},
        ),
    ]
